kind: Deployment
apiVersion: apps/v1
metadata:
  name: helloworld # the name displayed in the first column of 'kubectl get pods'
  namespace: helloworld
  labels:
    app: helloworld # this tag is added to help this object to link to the service object.
spec:
  replicas: 2
  minReadySeconds: 30 # wait before considering pods ready, check with kubectl rollout status
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: httpd:latest
          ports: # this bit is purely for informational purposes only and can be omitted.
            - containerPort: 80 # what port the container will be listening on
