---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp # the name displayed in the first column of 'kubectl get pods'
  labels:
    app: apache_webserver # this tag is added to help this object to link to the service object.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache_webserver
  template:
    metadata:
      labels:
        app: apache_webserver
    spec:
      containers:
        - image: httpd:latest # using the official apache image from docker hub, along with a tag
          ports: # this bit is purely for informational purposes only and can be omitted.
            - containerPort: 80 # what port the container will be listening on
